### ISSUE TITLE
Python client incorrectly returns "Server has started successfully" 

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#108]
Right now the Python client returns 

``` 
Server has started successfully.
```

when a 204 status code is returned.

Specifically, I observe this when the path to a Python code file or model file is incorrectly specified. 

https://github.com/KonduitAI/konduit-serving/blob/37b265d173ba8287f07f3c9785a258351f06ae36/python/konduit/server.py#L130-L131

## Steps to reproduce 

Consider the following YAML file: 

```yaml
serving:
  http_port: 1337
  input_data_format: NUMPY
  output_data_format: NUMPY
  log_timings: True
  extra_start_args: -Xmx8g
steps:
  python_step:
    type: PYTHON
    python_path: .
    python_code_path: ../python/simple.py
    python_inputs:
      first: NDARRAY
    python_outputs:
      second: NDARRAY
client:
    port: 1337
```

Now serve the model: 
```python
from konduit.load import server_from_file
server_from_file("../yaml/bad_output.yaml")
```

Output returned 

```
Starting server...

Server has started successfully.
```
