### ISSUE TITLE
python_path in yaml (possibly config.json) should be OS independent

### ISSUE THREAD

**Issue by wmeddie** [KonduitAI/konduit-serving#153]
The python_path parameter of the python step currently requires different values if it's running or Windows or Unix so if someone clones an example they have to manually fix it for their system to run it.  It would be nice if would parse the path by itself and make the necessary changes per OS.  Alternatively we could have it be a yaml list to make it explicit that we are doing some magic. (Possibly supporting something like http urls or something in the future)

```yaml
python_step:
  type: PYTHON
  python_paths:
    - .
    - ./venv
```
