### ISSUE TITLE
input_data_types/input_names redundancy in ModelSteps

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#168]
In `PythonStep`s, users can simply specify the type mapping in a YAML config without re-declaring the input names. 

```yaml
steps:
  python_step:
    type: PYTHON
    python_path: .
    python_code_path: ./simple.py
    python_inputs:
      first: NDARRAY
    python_outputs:
      second: NDARRAY
```
However, ModelSteps require input names and type mappings to be specified. 

## Expected behaviour

Specifying the type mapping should make re-specifying the input names unnecessary - we should just copy the keys of the `input_data_types` dictionary to `input_names`. 

## Example
Starting a server from the following YAML file extract:
```yaml
steps:
  tensorflow_step:
    type: TENSORFLOW
    model_loading_path: ../data/mnist/mnist_2.0.0.pb
    output_names:
      - output_layer/Softmax
    input_data_types:
      input_layer: FLOAT
    parallel_inference_config:
      workers: 1
```

will return the following exception:
```
java.lang.IllegalStateException: Unable to instantiate pipeline step from class ai.konduit.serving.pipeline.steps.InferenceExecutionerStepRunner 
...
Caused by: java.lang.IllegalStateException: java.lang.NullPointerException: No input names specified!   
```
